Miguel
FelipeWyatt/PROJETO2_JAVA pull request #8
Opened 2021-01-10 06:03 UTC by miguelsr692

Implementação métodos abstratos em ContaBancaria e em Investimentos.

2021-01-11 01:05 UTC, FelipeWyatt requested changes
Ótimo trabalho Miguel!
Só anotei alguns comentários que precisam de mudanças.

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +            Acao novo_investimento = new Acao(acao, quantidade, acao.precoTempoReal(), new GregorianCalendar());
Acho que aqui deve ser o seguinte para funcionar o polimorfismo:
Investimento novo_investimento = new Acao(...);

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +                    if(((Acao) i).getAcao() == acao && quantidade >= ((Acao) i).getQuantidade()) {
Aqui deve ser possível o usuário vender menos ações do que o investimento possui, por exemplo se ele tivesse 10.000 ações de uma empresa e o preço sobe, ele pode querer vender 4.000 delas...
Aconselho colocar um else if (quantidade < (Acao) i).getQuantidade()){...}

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +                        getInvestimentos().remove(i);
Nesse segundo caso que comentei, não deve-se retirar o Investimento do Array-List, só diminuir a quantidade de ações e o montante

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +                        setSaldo(getSaldo() + lucro); //diferença de preços da acao em dias diferentes
Quando compra uma ação, retira-se dinheiro do saldo da Conta e coloca no montante do Investimento, então quando vender uma ação deve-se transferir todo o montante para o saldo da Conta, não somente o lucro!

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +            Acao novo_investimento = new Acao(acao, quantidade, acao.precoTempoReal(), new GregorianCalendar());
Pois o ArrayList investimentos é de objeto Investimento não objetos específicos Acao

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/ContaInvestidor.java
> +            i.rendeInvestimento(diasPassados);
Adicionar comentário indicando Polimorfismo

2021-01-11 01:05 UTC, FelipeWyatt commented on src/com/company/Main.java
> +                cliente.getConta().rendeConta(diasPassados);
Que beleza esse polimosfismo hein!
Colocar comentário indicando uso do polimosfismo.

2021-01-12 04:06 UTC, miguelsr692 commented on src/com/company/ContaInvestidor.java
> +                        setSaldo(getSaldo() + lucro); //diferença de preços da acao em dias diferentes
Acho que não entendi muito bem. No caso já não é feito isso? O lucro é proporcional à quantidade de cotas que o cliente quer retirar do investimento. Se eu tenho 10 cotas, e quero retirar 6, o lucro vai ser a diferença dos valores de compra e venda, multiplicado por 6. Esse valor, como não vai mais estar investido, voltará para o saldo da conta, e as 4 cotas que restaram continuarão investidas, portanto ainda haverá um montante no investimento (4*precoTempoReal) já que elas não foram retiradas. Por que eu deveria transferir todo o valor do montante (10*precoTempoReal) se eu só retirei parte dele? Entendo que como o dinheiro ainda está investido, não deve estar disponível para saques, por exemplo, e portanto não deveria fazer parte da variável saldo. Adicionei um comado nessa rotina para atualizar o valor do montante com base no novo preço da ação, utilizando o método rendeInvestimento, acredito que assim, o dinheiro total do cliente estará atualizado, mas o saldo continuará se referindo apenas à quantidade de ações vendidas. Estou certo?

2021-01-12 04:39 UTC, FelipeWyatt approved these changes
Lançou a braba boa

2021-01-12 04:42 UTC, merged